export const prepositionArray = [
    "the", "etc", "of", "but", "so", "in", "to", "per",
    "as",
    "till",
    "on",
    "a",
    "an",
    "for",
    "our",
    "mine",
    "yours",
    "his",
    "hers",
    "theirs",
    "at",
    "and",
    "my",
  ]